# Описываем Виртуальные машины
MACHINES = {
  # Указываем имя ВМ "kernel update"
  :"kernel-update" => {
              ### На CentOS 8 из методички падает ядро ###
              #Какой vm box будем использовать
              :box_name => "generic/centos9s",
              #Указываем box_version
              :box_version => "4.3.4",
              ###Мне не критично, ресурсов не жалко.###
              #Указываем количество ядер ВМ
              :cpus => 4,
              #Указываем количество ОЗУ в мегабайтах. 
              :memory => 4096,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем проброс общей папки в ВМ
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
    end
  end
end