- name: NGINX | Install and configure NGINX
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:
# чиним пакеты
    - name: DNSSEC | DISABLE
      ini_file:
        path: /etc/systemd/resolved.conf
        section: 'Resolve'
        option: 'DNSSEC'
        value: 'no'
      tags:
        - DNSSEC disable

    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
      tags:
        - DNSSEC disable

    - name: update
      apt:
        update_cache=yes
      tags:
        - update apt

    - name: NGINX | Install NGINX
      apt:
        name: nginx
        state: latest
      tags:
        - nginx-package

    - name: NGINX | Create NGINX config file from template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
