# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :nginx => {
    :box_name => "generic/ubuntu2204",
    :vm_name => "nginx",
    :public => { type: "dhcp" } 
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = 2024
        v.cpus = 2
      end

      # Настройка публичной сети
      if boxconfig.key?(:public)
        box.vm.network "public_network", **boxconfig[:public]
      end

      # Провиженинг для настройки SSH
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/\\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end
  end
end
